version: '3.9'

networks:
  task8_default:
    driver: bridge

volumes:
  postgres_data:

services:
  # Backend
  backend:
    build: ./backend-demo
    container_name: backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://kanban-postgres:5432/kanban
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - kanban-postgres
    networks:
      - task8_default

  # Frontends
  frontend1:
    build: ./frontend-demo
    container_name: frontend1
    expose:
      - "80"
    networks:
      - task8_default

  frontend2:
    build: ./frontend-demo
    container_name: frontend2
    expose:
      - "80"
    networks:
      - task8_default

  # Nginx
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "18080:18080"
    depends_on:
      - frontend1
      - frontend2
      - backend
    networks:
      - task8_default
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl

  # Nginx Prometheus Exporter
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    command: ["--nginx.scrape-uri", "http://nginx:18080/stub_status"]
    networks:
      - task8_default

  # PostgreSQL
  kanban-postgres:
    image: postgres:13
    container_name: kanban-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: kanban
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - task8_default

  # PostgreSQL Exporter
  postgres-exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://myuser:mypassword@kanban-postgres:5432/kanban?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - kanban-postgres
    networks:
      - task8_default

  # Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - task8_default

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - nginx-exporter
      - postgres-exporter
      - node-exporter
      - loki
      - promtail
      - grafana
    networks:
      - task8_default

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - task8_default

  # Loki
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - task8_default

  # Promtail
  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
    depends_on:
      - loki
    networks:
      - task8_default
