global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'postgres'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'loki'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['promtail:9080']
