version: '3.9'

services:
  backend:
    build: ./backend-demo
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://kanban-postgres:5432/kanban
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - kanban-postgres
    logging:
      driver: "json-file"

  frontend1:
    build: ./frontend-demo
    container_name: frontend1
    expose:
      - "80"
    logging:
      driver: "json-file"

  frontend2:
    build: ./frontend-demo
    container_name: frontend2
    expose:
      - "80"
    logging:
      driver: "json-file"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend1
      - frontend2
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    logging:
      driver: "json-file"

  kanban-postgres:
    image: postgres:13
    container_name: kanban-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: kanban
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/alexlin/my-project/task7/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
    depends_on:
      - loki

volumes:
  postgres_data:
